# Generated by Django 2.1.2 on 2018-10-15 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='friends',
            field=models.ManyToManyField(related_name='_student_friends_+', to='friends.Student'),
        ),
    ]
